import { Nav } from '../components/layout'
import { IconDownload } from '../lib/icons'

interface ReportData {
  case_ref: string
  input_address: string
  chain: string
  fraud_type: string
  hop_count: number
  cluster_size: number
  mixer_exposure: number
  risk_score: number
  risk_band: string
  attributed_vasp_name: string | null
  attributed_vasp_address: string | null
  created_at: string
  graph: {
    nodes: any[]
    edges: any[]
    timeline: { hop: number; minutesElapsed: number; note: string }[]
  }
}

export const ReportPage = ({ data }: { data: ReportData }) => {
  const createdDate = new Date(data.created_at + 'Z')
  const totalAmount = data.graph.edges.length > 0 ? data.graph.edges[0].amount : 0

  return (
    <>
      <Nav />
      <button class="btn btn-primary report-print-btn" onclick="window.print()">
        <IconDownload style="width:15px;height:15px" /> Print / Save PDF
      </button>
      <div class="report-shell" style="padding-top:96px">
        <div class="report-paper">
          <div class="report-letterhead">
            <div>
              <div class="lh-title">CRYPTO-ATTRIB // I4C</div>
              <div class="lh-sub">Wallet Attribution &amp; Risk Assessment Report</div>
            </div>
            <div class="lh-ref">
              {data.case_ref}
              <br />
              <span style="font-family:Inter,sans-serif;font-size:11px;color:#8891A3;font-weight:400">
                Generated {createdDate.toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}
              </span>
            </div>
          </div>

          <div class="report-section">
            <h3>Case Summary</h3>
            <div class="report-kv"><div class="k">Case Reference</div><div class="v">{data.case_ref}</div></div>
            <div class="report-kv"><div class="k">Reported Wallet Address</div><div class="v" style="word-break:break-all;font-family:monospace;font-size:12.5px">{data.input_address}</div></div>
            <div class="report-kv"><div class="k">Source Chain</div><div class="v">{data.chain}</div></div>
            <div class="report-kv"><div class="k">Reported Fraud Type</div><div class="v">{data.fraud_type}</div></div>
            <div class="report-kv"><div class="k">Estimated Amount Traced</div><div class="v">₹{Math.round(totalAmount).toLocaleString('en-IN')}</div></div>
          </div>

          <div class="report-section">
            <h3>Trace Results</h3>
            <div class="report-kv"><div class="k">Hops to Endpoint</div><div class="v">{data.hop_count}</div></div>
            <div class="report-kv"><div class="k">Clustered Wallets</div><div class="v">{data.cluster_size}</div></div>
            <div class="report-kv"><div class="k">Mixer/Tumbler Exposure</div><div class="v">{data.mixer_exposure ? 'Detected' : 'None detected'}</div></div>
            <div class="report-kv"><div class="k">Risk Score</div><div class="v">{data.risk_score} / 100 — {data.risk_band}</div></div>
          </div>

          <div class="report-section">
            <h3>Exchange Attribution</h3>
            {data.attributed_vasp_name ? (
              <>
                <div class="report-kv"><div class="k">Attributed Exchange</div><div class="v">{data.attributed_vasp_name}</div></div>
                <div class="report-kv"><div class="k">Deposit Address</div><div class="v" style="word-break:break-all;font-family:monospace;font-size:12.5px">{data.attributed_vasp_address}</div></div>
                <p style="font-size:13px;color:#5A6478;margin-top:10px;font-style:italic">
                  Recommend an immediate freeze request to the identified exchange's compliance/LEA liaison desk,
                  citing this case reference and the full hop-by-hop trail below.
                </p>
              </>
            ) : (
              <p style="font-size:13.5px;color:#5A6478">
                No VASP registry match was found on the final traced hop. This endpoint has been flagged for
                manual registry enrichment and continued monitoring.
              </p>
            )}
          </div>

          <div class="report-section">
            <h3>Hop-by-Hop Timeline</h3>
            {data.graph.timeline.map((t) => (
              <div class="report-kv">
                <div class="k">Hop {t.hop} (T+{t.minutesElapsed}m)</div>
                <div class="v" style="font-weight:400">{t.note}</div>
              </div>
            ))}
          </div>

          <div class="report-section" style="margin-bottom:0">
            <h3>Chain of Custody</h3>
            <p style="font-size:12.5px;color:#8891A3">
              This report was generated by the Real-Time Crypto Fraud Attribution System's automated tracing and
              scoring pipeline. All figures are derived from a deterministic, reproducible trace run against the
              seeded demo dataset. In a production deployment this section would embed the live on-chain
              transaction hashes for every hop, source API attestations, and an investigator's digital signature.
            </p>
          </div>
        </div>
      </div>
    </>
  )
}
